openapi: 3.0.0
info:
  title: <% title %>
  version: 1.0.0

paths:
  /ws/stub:
    x-yc-apigateway-websocket-connect:
      summary: WS connections from stub function - accept without fn call
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          '*': ''
  /ws/client:
    x-yc-apigateway-websocket-connect:
      summary: WS connections from local client - accept and store connection info in db
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: <% store_fn_id %>
        tag: $latest
        service_account_id: <% sa_id %>
  /{path+}:
    x-yc-apigateway-any-method:
      summary: HTTP request to stub function - proxy to local code
      parameters:
        - name: path
          in: path
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: <% stub_fn_id %>
        tag: $latest
        service_account_id: <% sa_id %>

